# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'strategy.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(449, 634)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_11.addWidget(self.lineEdit)
        self.pushButton_42 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_42.setObjectName("pushButton_42")
        self.horizontalLayout_11.addWidget(self.pushButton_42)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_5.addWidget(self.pushButton_3)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_6.addWidget(self.pushButton_4)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_7.addWidget(self.pushButton_5)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_3.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_3.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_3.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_3.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_3.addWidget(self.pushButton_15)
        self.pushButton_15.raise_()
        self.pushButton_11.raise_()
        self.pushButton_12.raise_()
        self.pushButton_13.raise_()
        self.pushButton_14.raise_()
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_27 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_27.setObjectName("pushButton_27")
        self.horizontalLayout_6.addWidget(self.pushButton_27)
        self.pushButton_28 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_28.setObjectName("pushButton_28")
        self.horizontalLayout_6.addWidget(self.pushButton_28)
        self.pushButton_29 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_29.setObjectName("pushButton_29")
        self.horizontalLayout_6.addWidget(self.pushButton_29)
        self.pushButton_26 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_6.addWidget(self.pushButton_26)
        self.pushButton_30 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_30.setObjectName("pushButton_30")
        self.horizontalLayout_6.addWidget(self.pushButton_30)
        self.verticalLayout.addWidget(self.groupBox_8)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_5.addWidget(self.pushButton_21)
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_5.addWidget(self.pushButton_22)
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_5.addWidget(self.pushButton_23)
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_5.addWidget(self.pushButton_24)
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_5.addWidget(self.pushButton_25)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_31 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_31.setObjectName("pushButton_31")
        self.horizontalLayout_7.addWidget(self.pushButton_31)
        self.pushButton_32 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_32.setObjectName("pushButton_32")
        self.horizontalLayout_7.addWidget(self.pushButton_32)
        self.pushButton_33 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_33.setObjectName("pushButton_33")
        self.horizontalLayout_7.addWidget(self.pushButton_33)
        self.pushButton_34 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_34.setObjectName("pushButton_34")
        self.horizontalLayout_7.addWidget(self.pushButton_34)
        self.pushButton_35 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_35.setObjectName("pushButton_35")
        self.horizontalLayout_7.addWidget(self.pushButton_35)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_37 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_37.setObjectName("pushButton_37")
        self.horizontalLayout_8.addWidget(self.pushButton_37)
        self.pushButton_38 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_38.setObjectName("pushButton_38")
        self.horizontalLayout_8.addWidget(self.pushButton_38)
        self.pushButton_39 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_39.setObjectName("pushButton_39")
        self.horizontalLayout_8.addWidget(self.pushButton_39)
        self.pushButton_40 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_40.setObjectName("pushButton_40")
        self.horizontalLayout_8.addWidget(self.pushButton_40)
        self.pushButton_41 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_41.setObjectName("pushButton_41")
        self.horizontalLayout_8.addWidget(self.pushButton_41)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_4.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_4.addWidget(self.pushButton_17)
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_4.addWidget(self.pushButton_18)
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_4.addWidget(self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_4.addWidget(self.pushButton_20)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_2.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_2.addWidget(self.pushButton_10)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.pushButton_43 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_43.setObjectName("pushButton_43")
        self.horizontalLayout_10.addWidget(self.pushButton_43)
        self.pushButton_36 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_36.setObjectName("pushButton_36")
        self.horizontalLayout_10.addWidget(self.pushButton_36)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 449, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Файл стратегии"))
        self.pushButton_42.setText(_translate("MainWindow", "Обзор"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Открытие"))
        self.label_2.setText(_translate("MainWindow", "0%"))
        self.pushButton.setText(_translate("MainWindow", "EP"))
        self.label_3.setText(_translate("MainWindow", "0%"))
        self.pushButton_2.setText(_translate("MainWindow", "MP"))
        self.label_4.setText(_translate("MainWindow", "0%"))
        self.pushButton_3.setText(_translate("MainWindow", "CO"))
        self.label_5.setText(_translate("MainWindow", "0%"))
        self.pushButton_4.setText(_translate("MainWindow", "BTN"))
        self.label_6.setText(_translate("MainWindow", "0%"))
        self.pushButton_5.setText(_translate("MainWindow", "SB"))
        self.groupBox.setTitle(_translate("MainWindow", "Изолейт"))
        self.pushButton_11.setText(_translate("MainWindow", "MP"))
        self.pushButton_12.setText(_translate("MainWindow", "CO"))
        self.pushButton_13.setText(_translate("MainWindow", "BTN"))
        self.pushButton_14.setText(_translate("MainWindow", "SB"))
        self.pushButton_15.setText(_translate("MainWindow", "BB"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Колл 3бета"))
        self.pushButton_27.setText(_translate("MainWindow", "vs MP"))
        self.pushButton_28.setText(_translate("MainWindow", "vs CO"))
        self.pushButton_29.setText(_translate("MainWindow", "vs BTN"))
        self.pushButton_26.setText(_translate("MainWindow", "vs SB"))
        self.pushButton_30.setText(_translate("MainWindow", "vs BB"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Колл в холодную"))
        self.pushButton_21.setText(_translate("MainWindow", "MP"))
        self.pushButton_22.setText(_translate("MainWindow", "CO"))
        self.pushButton_23.setText(_translate("MainWindow", "BTN"))
        self.pushButton_24.setText(_translate("MainWindow", "SB"))
        self.pushButton_25.setText(_translate("MainWindow", "BB"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Сквиз"))
        self.pushButton_31.setText(_translate("MainWindow", "MP"))
        self.pushButton_32.setText(_translate("MainWindow", "CO"))
        self.pushButton_33.setText(_translate("MainWindow", "BTN"))
        self.pushButton_34.setText(_translate("MainWindow", "SB"))
        self.pushButton_35.setText(_translate("MainWindow", "BB"))
        self.groupBox_5.setTitle(_translate("MainWindow", "5bet"))
        self.pushButton_37.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_38.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_39.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_40.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_41.setText(_translate("MainWindow", "PushButton"))
        self.groupBox_4.setTitle(_translate("MainWindow", "4bet"))
        self.pushButton_16.setText(_translate("MainWindow", "vs MP"))
        self.pushButton_17.setText(_translate("MainWindow", "vs CO"))
        self.pushButton_18.setText(_translate("MainWindow", "vs BTN"))
        self.pushButton_19.setText(_translate("MainWindow", "vs SB"))
        self.pushButton_20.setText(_translate("MainWindow", "vs BB"))
        self.groupBox_2.setTitle(_translate("MainWindow", "3bet"))
        self.pushButton_6.setText(_translate("MainWindow", "vs EP"))
        self.pushButton_7.setText(_translate("MainWindow", "vs MP"))
        self.pushButton_8.setText(_translate("MainWindow", "vs CO"))
        self.pushButton_9.setText(_translate("MainWindow", "vs BTN"))
        self.pushButton_10.setText(_translate("MainWindow", "vs SB"))
        self.pushButton_43.setText(_translate("MainWindow", "Применить"))
        self.pushButton_36.setText(_translate("MainWindow", "Сохранить"))
